function L2Step11() {
  const appPy = [
    "# Урок 2: Список дел (To-Do) — данные в памяти",
    "from flask import Flask, render_template, request, jsonify",
    "",
    "app = Flask(__name__)",
    "app.config['DEBUG'] = True",
    "",
    "todos = []",
    "next_id = 1",
    "",
    "@app.route('/')",
    "def index():",
    "    return render_template('index.html')",
    "",
    "@app.route('/api/todos', methods=['GET'])",
    "def get_todos():",
    "    return jsonify({'todos': todos})",
    "",
    "@app.route('/api/todos', methods=['POST'])",
    "def add_todo():",
    "    global next_id",
    "    data = request.json or {}",
    "    text = (data.get('text') or '').strip()",
    "    if not text:",
    "        return jsonify({'success': False, 'error': 'Введите текст дела!'}), 400",
    "    todo = {'id': next_id, 'text': text, 'done': False}",
    "    next_id += 1",
    "    todos.append(todo)",
    "    return jsonify({'success': True, 'todo': todo})",
    "",
    "@app.route('/api/todos/<int:todo_id>/toggle', methods=['POST'])",
    "def toggle_todo(todo_id):",
    "    for t in todos:",
    "        if t['id'] == todo_id:",
    "            t['done'] = not t['done']",
    "            return jsonify({'success': True, 'todo': t})",
    "    return jsonify({'success': False, 'error': 'Дело не найдено'}), 404",
    "",
    "@app.route('/api/todos/<int:todo_id>', methods=['DELETE'])",
    "def delete_todo(todo_id):",
    "    global todos",
    "    for i, t in enumerate(todos):",
    "        if t['id'] == todo_id:",
    "            todos.pop(i)",
    "            return jsonify({'success': True})",
    "    return jsonify({'success': False, 'error': 'Дело не найдено'}), 404",
    "",
    "if __name__ == '__main__':",
    "    app.run(host='0.0.0.0', port=5001, debug=True)"
  ].join('\n')

  const indexHtml = [
    "<!DOCTYPE html>",
    "<html lang=\"ru\">",
    "<head>",
    "    <meta charset=\"UTF-8\">",
    "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">",
    "    <title>Список дел — Урок 2</title>",
    "    <link rel=\"stylesheet\" href=\"/static/style.css\">",
    "</head>",
    "<body>",
    "    <div class=\"container\">",
    "        <h1>📋 Список дел</h1>",
    "        <p class=\"subtitle\">Урок 2: несколько маршрутов, данные в памяти</p>",
    "",
    "        <div class=\"add-form\">",
    "            <input type=\"text\" id=\"newTodo\" placeholder=\"Новое дело...\" maxlength=\"200\">",
    "            <button type=\"button\" id=\"addBtn\">Добавить</button>",
    "        </div>",
    "",
    "        <ul id=\"todoList\" class=\"todo-list\"></ul>",
    "        <p id=\"emptyMsg\" class=\"empty-msg\">Пока пусто. Добавьте первое дело!</p>",
    "    </div>",
    "",
    "    <script src=\"/static/script.js\"></script>",
    "</body>",
    "</html>"
  ].join('\n')

  const scriptJs = [
    "document.addEventListener('DOMContentLoaded', function() {",
    "    const newTodo = document.getElementById('newTodo');",
    "    const addBtn = document.getElementById('addBtn');",
    "    const list = document.getElementById('todoList');",
    "    const emptyMsg = document.getElementById('emptyMsg');",
    "",
    "    function showEmpty(show) {",
    "        emptyMsg.classList.toggle('visible', show);",
    "    }",
    "",
    "    function renderItem(t) {",
    "        const li = document.createElement('li');",
    "        if (t.done) li.classList.add('done');",
    "        li.dataset.id = t.id;",
    "        li.innerHTML = `",
    "            <span class=\"text\">${escapeHtml(t.text)}</span>",
    "            <button type=\"button\" class=\"toggle\">${t.done ? '↩ Вернуть' : '✓ Готово'}</button>",
    "            <button type=\"button\" class=\"del\">✕</button>",
    "        `;",
    "        li.querySelector('.toggle').addEventListener('click', () => toggle(t.id));",
    "        li.querySelector('.del').addEventListener('click', () => remove(t.id));",
    "        return li;",
    "    }",
    "",
    "    function escapeHtml(s) {",
    "        const div = document.createElement('div');",
    "        div.textContent = s;",
    "        return div.innerHTML;",
    "    }",
    "",
    "    function load() {",
    "        fetch('/api/todos')",
    "            .then(r => r.json())",
    "            .then(data => {",
    "                list.innerHTML = '';",
    "                data.todos.forEach(t => list.appendChild(renderItem(t)));",
    "                showEmpty(data.todos.length === 0);",
    "            });",
    "    }",
    "",
    "    function add() {",
    "        const text = newTodo.value.trim();",
    "        if (!text) return;",
    "        fetch('/api/todos', {",
    "            method: 'POST',",
    "            headers: { 'Content-Type': 'application/json' },",
    "            body: JSON.stringify({ text: text })",
    "        })",
    "            .then(r => r.json())",
    "            .then(data => {",
    "                if (data.success) {",
    "                    newTodo.value = '';",
    "                    list.appendChild(renderItem(data.todo));",
    "                    showEmpty(false);",
    "                }",
    "            });",
    "    }",
    "",
    "    function toggle(id) {",
    "        fetch(`/api/todos/${id}/toggle`, { method: 'POST' })",
    "            .then(r => r.json())",
    "            .then(data => {",
    "                if (data.success) load();",
    "            });",
    "    }",
    "",
    "    function remove(id) {",
    "        fetch(`/api/todos/${id}`, { method: 'DELETE' })",
    "            .then(r => r.json())",
    "            .then(data => {",
    "                if (data.success) {",
    "                    const li = list.querySelector(`[data-id=\"${id}\"]`);",
    "                    if (li) li.remove();",
    "                    showEmpty(list.children.length === 0);",
    "                }",
    "            });",
    "    }",
    "",
    "    addBtn.addEventListener('click', add);",
    "    newTodo.addEventListener('keypress', function(e) {",
    "        if (e.key === 'Enter') add();",
    "    });",
    "",
    "    load();",
    "});"
  ].join('\n')

  const styleCss = [
    "* { margin: 0; padding: 0; box-sizing: border-box; }",
    "",
    "body {",
    "    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;",
    "    background: linear-gradient(135deg, #11998e 0%, #38ef7d 100%);",
    "    min-height: 100vh;",
    "    display: flex;",
    "    justify-content: center;",
    "    align-items: flex-start;",
    "    padding: 40px 20px;",
    "}",
    "",
    ".container {",
    "    background: white;",
    "    border-radius: 16px;",
    "    box-shadow: 0 10px 40px rgba(0,0,0,0.15);",
    "    padding: 32px;",
    "    max-width: 520px;",
    "    width: 100%;",
    "}",
    "",
    "h1 { color: #333; margin-bottom: 4px; font-size: 1.8em; }",
    ".subtitle { color: #666; font-size: 0.9em; margin-bottom: 24px; }",
    "",
    ".add-form {",
    "    display: flex;",
    "    gap: 10px;",
    "    margin-bottom: 24px;",
    "}",
    "",
    ".add-form input {",
    "    flex: 1;",
    "    padding: 12px 14px;",
    "    border: 2px solid #e0e0e0;",
    "    border-radius: 8px;",
    "    font-size: 16px;",
    "}",
    ".add-form input:focus {",
    "    outline: none;",
    "    border-color: #11998e;",
    "}",
    "",
    ".add-form button {",
    "    padding: 12px 20px;",
    "    background: linear-gradient(135deg, #11998e 0%, #38ef7d 100%);",
    "    color: white;",
    "    border: none;",
    "    border-radius: 8px;",
    "    font-weight: 600;",
    "    cursor: pointer;",
    "}",
    ".add-form button:hover { opacity: 0.9; }",
    "",
    ".todo-list { list-style: none; }",
    ".todo-list li {",
    "    display: flex;",
    "    align-items: center;",
    "    gap: 10px;",
    "    padding: 12px 14px;",
    "    background: #f5f5f5;",
    "    border-radius: 8px;",
    "    margin-bottom: 8px;",
    "}",
    ".todo-list li.done { opacity: 0.6; }",
    ".todo-list li.done .text { text-decoration: line-through; color: #888; }",
    "",
    ".todo-list .text { flex: 1; }",
    ".todo-list .toggle, .todo-list .del {",
    "    padding: 6px 12px;",
    "    border: none;",
    "    border-radius: 6px;",
    "    cursor: pointer;",
    "    font-size: 13px;",
    "}",
    ".todo-list .toggle { background: #e3f2fd; color: #1976d2; }",
    ".todo-list .del { background: #ffebee; color: #c62828; }",
    "",
    ".empty-msg { color: #999; text-align: center; padding: 24px; display: none; }",
    ".empty-msg.visible { display: block; }"
  ].join('\n')

  return (
    <div className="step-content trainer-step">
      <h2>Готовые файлы — копируй и вставляй</h2>

      <p>Ниже — полный набор файлов, которые ты можешь создать в проекте. Просто создай структуру:</p>
      <ol>
        <li>Папка проекта</li>
        <li>Создай virtualenv и установи Flask</li>
        <li>Создай файл <code>app.py</code></li>
        <li>Создай папки <code>templates</code> и <code>static</code></li>
        <li>Создай <code>templates/index.html</code>, <code>static/script.js</code>, <code>static/style.css</code></li>
      </ol>

      <h3>app.py</h3>
      <div className="code-block"><code>{appPy}</code></div>

      <h3>templates/index.html</h3>
      <div className="code-block"><code>{indexHtml}</code></div>

      <h3>static/script.js</h3>
      <div className="code-block"><code>{scriptJs}</code></div>

      <h3>static/style.css</h3>
      <div className="code-block"><code>{styleCss}</code></div>

      <div className="success-box">
        <strong>✅ Совет:</strong> сначала скопируй все файлы, запусти сервер и проверь, потом проходи шаги урока, сравнивая свой код с этими примерами.
      </div>
    </div>
  )
}

export default L2Step11

